
import ToastProvider from '@/components/common/notification/toasProvider'
import { Open_Sans } from 'next/font/google'
import AppProvider from "."
import "../styles/globals.css"

export const metadata = {
  title: 'Color-Ecommerce',
  description: 'Generated by Next.js',
}

const openSan = Open_Sans({ subsets: ['vietnamese'] })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={openSan.className}>
        <ToastProvider>
          <AppProvider>
            {children}
          </AppProvider>
        </ToastProvider>
      </body>
    </html>
  )
}
