
import "../styles/globals.css"

export const metadata = {
  title: 'Color-Ecommerce',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className="hihihi">{children}</body>
    </html>
  )
}
